'use client'
import Nav from '@/components/Nav'
import './globals.css'
import Provider from '@/components/Provider'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


export const metadata = {
  title: 'Admin Panel',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Provider>
          <div className="main">
            <div className="gradient" />
          </div>
          <main className="app">
            <Nav />
            <ToastContainer theme='dark'/>
            {children}
          </main>
        </Provider>
      </body>
    </html>
  )
}
